version: '3.8'

services:
  web:
    build: .
    container_name: api_e_money
    ports:
      - "7890:7890"
    environment:
      - GIN_MODE=release
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: db_e_money
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: